### ISSUE TITLE
对不起…我想问个很傻的问题

### ISSUE THREAD

**Issue by GitHubAFeng** [Clark-Zhao/vue-components#1]
不在npm环境下如何引用组件呢？ 我是后端的，很少使用npm

**Comment by LLawlight** [comment]
@GitHubAFeng 你是想静态的引用吗？引入vuejs2.0之后直接引用libs文件夹里面的z-vue-components.js或者z-vue-components.min.js就可以了

```
<script src="path/to/vue.js"></script>
<script src="path/to/z-vue-components.js"></script>
<script>
  var vm = new Vue({
    components: {
      zButton: ZVueComponents.zButton
    },
    el: "#app"
  })
</script>

<z-button
:text="'Hello world!'">
</z-button>
```

**Comment by GitHubAFeng** [comment]
感谢回答问题。 原来还发布了静态库，这个好。 我好奇一下，如果没有现成的lib ， 我怎么在项目中引用组件呢？  src目录里的资源

**Comment by LLawlight** [comment]
@GitHubAFeng 直接调用src/components里面的vue文件就可以单独使用某一个组件，html，css和js都写在一个vue文件里面的，如果你的项目不支持vue格式，也可以单独把他们拿出来注册组件
